<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MicroCapture.UI\MicroCapture.UI.csproj" />
    <ProjectReference Include="..\..\MicroCapture.Camera\MicroCapture.Camera.csproj" />
    <ProjectReference Include="..\..\MicroCapture.Core\MicroCapture.Core.csproj" />
  </ItemGroup>
</Project>
