// <auto-generated />
using System;
using MicroCapture.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroCapture.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MicroCapture.Core.Models.Batch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BinarizeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BleedthroughEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraCalibrationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DewarpEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dpi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FixedFrameImageHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixedFrameImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FixedFrames")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredExportFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SplitBookPages")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseFixedFrames")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WatermarkEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WatermarkPresetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraCalibrationId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WatermarkPresetId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("MicroCapture.Core.Models.CameraCalibration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalibratedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraMatrix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DistCoeffs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("MeasuredPixelHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("MeasuredPixelWidth")
                        .HasColumnType("REAL");

                    b.Property<double>("ReprojectionErrorPx")
                        .HasColumnType("REAL");

                    b.Property<double?>("TargetHeightInches")
                        .HasColumnType("REAL");

                    b.Property<double?>("TargetWidthInches")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CameraCalibrations");
                });

            modelBuilder.Entity("MicroCapture.Core.Models.CaptureJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Brightness")
                        .HasColumnType("REAL");

                    b.Property<string>("CaptureFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Contrast")
                        .HasColumnType("REAL");

                    b.Property<string>("DewarpCurve")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DewarpManualOverrideApplied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExportStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FlipHorizontal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlipVertical")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasManualAdjustments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeftCropBox")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManualOverrideApplied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OcrStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessedFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QcStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RightCropBox")
                        .HasColumnType("TEXT");

                    b.Property<int>("RotationDegrees")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Saturation")
                        .HasColumnType("REAL");

                    b.Property<double>("Sharpness")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("WhiteBalance")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("CaptureJobs");
                });

            modelBuilder.Entity("MicroCapture.Core.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MicroCapture.Core.Models.WatermarkPreset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FontFamily")
                        .HasColumnType("TEXT");

                    b.Property<double>("FontSize")
                        .HasColumnType("REAL");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("LogoImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Opacity")
                        .HasColumnType("REAL");

                    b.Property<double>("RotationDegrees")
                        .HasColumnType("REAL");

                    b.Property<string>("TextColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("WatermarkType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WatermarkPresets");
                });

            modelBuilder.Entity("MicroCapture.Core.Models.Batch", b =>
                {
                    b.HasOne("MicroCapture.Core.Models.CameraCalibration", "CameraCalibration")
                        .WithMany()
                        .HasForeignKey("CameraCalibrationId");

                    b.HasOne("MicroCapture.Core.Models.Project", "Project")
                        .WithMany("Batches")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroCapture.Core.Models.WatermarkPreset", "WatermarkPreset")
                        .WithMany()
                        .HasForeignKey("WatermarkPresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CameraCalibration");

                    b.Navigation("Project");

                    b.Navigation("WatermarkPreset");
                });

            modelBuilder.Entity("MicroCapture.Core.Models.CaptureJob", b =>
                {
                    b.HasOne("MicroCapture.Core.Models.Batch", "Batch")
                        .WithMany("Captures")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MicroCapture.Core.Models.Batch", b =>
                {
                    b.Navigation("Captures");
                });

            modelBuilder.Entity("MicroCapture.Core.Models.Project", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
